name: scrape_matches
dependencies:
    - python=3.10
    - beautifulsoup4=4.11.1
    - black=22.6.0
    - flake8=4.0.1
    - isort=5.9.3
    - pandas=1.4.4
    - pytest=7.1.2
    - requests=2.28.1
    - jupyter
